name: "linter"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - run: npm clean-install
      - name: "prettier"
        run: npm run prettier:check
      - name: "audit"
        run: npm audit
